name: Python - Run all steps (Nightly Build)

on:
  schedule:
    - cron: 30 23 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run All Steps
      run: |
        python run_all_steps.py
    - name: Git Config
      run: |
        git config user.name 'Nya Îžlimu'
        git config user.email 'info@elimu.ai'
    - name: Git Commit
      run: |
        git add step1_prepare/*.csv
        git commit -m 'chore(ml): nightly build'
    - name: Git Push
      run: |
        git push
